# Generated by Django 2.2 on 2019-01-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, max_length=80, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='fixo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Fixo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=80, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='trabalho',
            field=models.CharField(blank=True, max_length=30, verbose_name='Trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='uf',
            field=models.CharField(blank=True, max_length=80, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='Whatsapp'),
        ),
    ]
