# Generated by Django 2.2 on 2019-01-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20190105_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo de barras'),
        ),
    ]
