# Generated by Django 2.2 on 2019-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20190202_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='status',
        ),
        migrations.AddField(
            model_name='produto',
            name='controle_estoque',
            field=models.BooleanField(blank=True, default=True, verbose_name='Fora de Linha'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fora_de_linha',
            field=models.BooleanField(blank=True, default=False, verbose_name='Fora de Linha'),
        ),
    ]
