# Generated by Django 2.2 on 2019-02-02 22:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20190202_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estoque Atual'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estoque Minimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='controle_estoque',
            field=models.BooleanField(blank=True, default=True, verbose_name='Controle de Estoque'),
        ),
    ]
