# Generated by Django 2.2 on 2018-08-17 18:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_auto_20180817_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1055)),
            ],
            options={
                'verbose_name': 'Local de Estoque',
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstocado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_produto_estocado', to='estoque.LocalEstoque')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_estocado', to='cadastro.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='localestoque',
            name='produtos_estoque',
            field=models.ManyToManyField(through='estoque.ProdutoEstocado', to='cadastro.Produto'),
        ),
    ]
