# Generated by Django 2.2 on 2018-08-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsaida',
            old_name='desconto',
            new_name='desconto_item',
        ),
    ]
