# Generated by Django 2.2 on 2018-08-19 01:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20180817_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementrada',
            name='desconto',
        ),
        migrations.AddField(
            model_name='itementrada',
            name='desconto_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='itemsaida',
            name='desconto_item',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto'),
        ),
    ]
