# Generated by Django 2.2 on 2018-08-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_produto_foto'),
        ('pedido', '0003_auto_20180819_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='cliente',
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Fornecedor'),
            preserve_default=False,
        ),
    ]
