# Generated by Django 2.2 on 2018-08-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20180819_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='chave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chave'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data Entrada'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='nf',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° NF'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='serie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Serie'),
        ),
    ]
