# Generated by Django 2.2 on 2019-02-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20190201_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='tipo_nota',
            new_name='tipo',
        ),
    ]
