# Generated by Django 2.2 on 2019-02-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20190201_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='chave',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Chave'),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='nota',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie'),
        ),
    ]
