# Generated by Django 2.2 on 2019-02-02 01:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20190202_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto do pedido'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='despesa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Despesa do pedido'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total do pedido'),
        ),
    ]
