# Generated by Django 2.2 on 2019-02-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_auto_20190202_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'EMITIDA'), (1, 'PENDENTE'), (2, 'CANCELADA')], max_length=20, null=True, verbose_name='STATUS'),
        ),
    ]
